# https://taskfile.dev

version: '3'

includes:
  clock:
    taskfile: ./clock
    dir: ./clock
  core:
    taskfile: ./core
    dir: ./core
  core-frontend:
    taskfile: ./core-frontend
    dir: ./core-frontend

tasks:
  create-network:
    cmd: docker network create app-os
    status:
      - docker network inspect app-os

  run:
    deps:
      - create-network
      - core:docker:rm
      - core:docker:build
      - core:install
      - core-frontend:docker:rm
      - core-frontend:docker:build
      - core-frontend:install
      - clock:docker:rm
      - clock:docker:build
      - clock:install
    cmds:
      - task: core:run

  apps:install:
    cmds:
      - cp core/appOS.manifest.json  config/apps.enabled/appos.core.json
      - cp clock/appOS.manifest.json config/apps.enabled/appos.test.clock.json
