# https://taskfile.dev

version: '3'

includes:
  clock:
    taskfile: ./clock
    dir: ./clock
  core:
    taskfile: ./core
    dir: ./core
  core-frontend:
    taskfile: ./core-frontend
    dir: ./core-frontend
  ui:
    taskfile: ./ui
    dir: ./ui

tasks:
  create-network:
    cmd: docker network create appos
    status:
      - docker network inspect appos

  run:
    deps:
      - create-network
      - core:docker:rm
      - core:docker:build
      # - core-frontend:docker:rm
      # - core-frontend:docker:build
      # - clock:docker:rm
      # - clock:docker:build
      # - ui:docker:rm
      # - ui:docker:build
    cmds:
      - task: core:docker:run
