# https://taskfile.dev

version: '3'

tasks:
  generate-protobuf:
    cmds:
      - protoc --proto_path=./schemas --go_opt=paths=source_relative --go_out=./pb --go-grpc_out=./pb --go-grpc_opt=paths=source_relative ./schemas/users.proto

  docker:build:
    cmd: docker build -t appos-core .
