# https://taskfile.dev

version: '3'

tasks:
  generate-protobuf:
    cmds:
      - protoc --proto_path=./schemas --go_opt=paths=source_relative --go_out=./internal/pb --go-grpc_out=./internal/pb --go-grpc_opt=paths=source_relative ./schemas/users.proto

  graphql:generate:
    cmd: go run github.com/99designs/gqlgen generate

  docker:build:
    cmd: docker build -t appos-core .

  docker:rm:
    cmds:
      - docker container rm appos-traefik -f
      - docker container rm appos.core -f

  docker:run:
    cmds:
      - mkdir -p {{.CONFIG_DIR}}/app-data/appos.core
      - docker run --volume {{.CONFIG_DIR}}:/config --volume {{.CONFIG_DIR}}/app-data/appos.core:/data --volume /var/run/docker.sock:/var/run/docker.sock:ro --network app-os --env CONFIG_DIR={{.CONFIG_DIR}} --name appos.core --rm appos-core
    vars:
      CONFIG_DIR:
        sh: readlink -f ../config

  install:
    cmd: cp appOS.manifest.json ../config/apps.enabled/appos.core.json 
  
  run:
    cmd: APP_OS_CONFIG_DIRECTORY={{.CONFIG_DIR}} CONFIG_DIR={{.CONFIG_DIR}} go run . run
    vars:
      CONFIG_DIR:
        sh: readlink -f ../config
