// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.23.4
// source: applications.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	ApplicationsService_ListInstalledApplications_FullMethodName = "/appos.core.ApplicationsService/ListInstalledApplications"
)

// ApplicationsServiceClient is the client API for ApplicationsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ApplicationsServiceClient interface {
	ListInstalledApplications(ctx context.Context, in *ListInstalledApplicationsRequest, opts ...grpc.CallOption) (*ListInstalledApplicationsResponse, error)
}

type applicationsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewApplicationsServiceClient(cc grpc.ClientConnInterface) ApplicationsServiceClient {
	return &applicationsServiceClient{cc}
}

func (c *applicationsServiceClient) ListInstalledApplications(ctx context.Context, in *ListInstalledApplicationsRequest, opts ...grpc.CallOption) (*ListInstalledApplicationsResponse, error) {
	out := new(ListInstalledApplicationsResponse)
	err := c.cc.Invoke(ctx, ApplicationsService_ListInstalledApplications_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ApplicationsServiceServer is the server API for ApplicationsService service.
// All implementations must embed UnimplementedApplicationsServiceServer
// for forward compatibility
type ApplicationsServiceServer interface {
	ListInstalledApplications(context.Context, *ListInstalledApplicationsRequest) (*ListInstalledApplicationsResponse, error)
	mustEmbedUnimplementedApplicationsServiceServer()
}

// UnimplementedApplicationsServiceServer must be embedded to have forward compatible implementations.
type UnimplementedApplicationsServiceServer struct {
}

func (UnimplementedApplicationsServiceServer) ListInstalledApplications(context.Context, *ListInstalledApplicationsRequest) (*ListInstalledApplicationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListInstalledApplications not implemented")
}
func (UnimplementedApplicationsServiceServer) mustEmbedUnimplementedApplicationsServiceServer() {}

// UnsafeApplicationsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ApplicationsServiceServer will
// result in compilation errors.
type UnsafeApplicationsServiceServer interface {
	mustEmbedUnimplementedApplicationsServiceServer()
}

func RegisterApplicationsServiceServer(s grpc.ServiceRegistrar, srv ApplicationsServiceServer) {
	s.RegisterService(&ApplicationsService_ServiceDesc, srv)
}

func _ApplicationsService_ListInstalledApplications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInstalledApplicationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApplicationsServiceServer).ListInstalledApplications(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ApplicationsService_ListInstalledApplications_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApplicationsServiceServer).ListInstalledApplications(ctx, req.(*ListInstalledApplicationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ApplicationsService_ServiceDesc is the grpc.ServiceDesc for ApplicationsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ApplicationsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "appos.core.ApplicationsService",
	HandlerType: (*ApplicationsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListInstalledApplications",
			Handler:    _ApplicationsService_ListInstalledApplications_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "applications.proto",
}
