package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.35

import (
	"context"

	"github.com/Season-04/app-os/core/internal/graph/model"
	"github.com/Season-04/app-os/core/internal/pb"
	"github.com/Season-04/app-os/core/types"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// Version is the resolver for the version field.
func (r *queryResolver) Version(ctx context.Context) (string, error) {
	return "1.0", nil
}

// Viewer is the resolver for the viewer field.
func (r *queryResolver) Viewer(ctx context.Context) (*model.User, error) {
	currentUser := r.CurrentUser(ctx)
	if currentUser == nil {
		return nil, nil
	}

	user := &pb.User{
		Id:           currentUser.ID,
		Name:         currentUser.Name,
		EmailAddress: currentUser.EmailAddress,
		LastSeenAt: &timestamppb.Timestamp{
			Seconds: 0,
			Nanos:   0,
		},
	}

	switch currentUser.Role {
	case types.UserRoleAdmin:
		user.Role = pb.UserRole_USER_ROLE_ADMIN
	default:
		user.Role = pb.UserRole_USER_ROLE_USER
	}

	if currentUser.LastSeenAt != nil {
		user.LastSeenAt = timestamppb.New(*currentUser.LastSeenAt)
	}

	return &model.User{User: user}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
