# https://taskfile.dev

version: '3'

tasks:
  docker:build:
    cmd: docker build -t appos-ui .

  docker:rm:
    cmd: docker container rm appos.ui -f

  install:
    cmd: cp appOS.manifest.json ../config/apps.enabled/appos.ui.json
